os: linux
dist: bionic

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta --depth=1
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter version 1.19.0-4.3.pre
  - flutter config --enable-web

script:
  - flutter build web

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/web