os: linux
dist: bionic

before_script:
  # use master branch to keep up with latest flutter web sdk,
  # hope this would lead to better performance
  - if cd flutter; then git pull && cd .. ; else git clone https://github.com/flutter/flutter.git -b master; fi
  #  - if cd flutter; then git pull && cd .. ; else git clone https://github.com/flutter/flutter.git -b beta; fi
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  #  - flutter doctor -v
  - flutter clean
  - flutter config --enable-web

script:
  - flutter build web --release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/web
  fqdn: nightly.thuhole.com